const DB_NAME='earth-ex-movies';const STORE='movies';let movies=[];let activeId=null;let activeUrl=null;const $=s=>document.querySelector(s);
function openDb(){return new Promise((resolve,reject)=>{const request=indexedDB.open(DB_NAME,1);request.onupgradeneeded=()=>request.result.createObjectStore(STORE,{keyPath:'id'});request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error)})}
async function allMovies(){const db=await openDb();return new Promise((resolve,reject)=>{const r=db.transaction(STORE).objectStore(STORE).getAll();r.onsuccess=()=>resolve(r.result.sort((a,b)=>a.title.localeCompare(b.title)));r.onerror=()=>reject(r.error)})}
async function putMovie(movie){const db=await openDb();return new Promise((resolve,reject)=>{const r=db.transaction(STORE,'readwrite').objectStore(STORE).put(movie);r.onsuccess=resolve;r.onerror=()=>reject(r.error)})}
async function removeMovie(id){const db=await openDb();return new Promise((resolve,reject)=>{const r=db.transaction(STORE,'readwrite').objectStore(STORE).delete(id);r.onsuccess=resolve;r.onerror=()=>reject(r.error)})}
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function poster(m){return m.poster?`background-image:url('${esc(m.poster)}')`:''}
function render(){const q=$('#search').value.toLowerCase();const shown=movies.filter(m=>`${m.title} ${m.genre} ${m.year}`.toLowerCase().includes(q));$('#featuredTitle').textContent=movies[0]?.title||'No movies yet';$('#storageNotice').textContent=movies.length?`${movies.length} movie${movies.length===1?'':'s'} stored on this device`:'Upload your first movie to get started.';$('#movies').innerHTML=shown.length?shown.map(m=>`<article class="movie" data-id="${m.id}"><div class="poster" style="${poster(m)}">${m.poster?'':'✦'}</div><div class="movie-copy"><p class="eyebrow">${esc(m.year||'EARTH-EX')} · ${esc(m.genre||'FEATURE')}</p><h3>${esc(m.title)}</h3><p>${esc(m.description||m.fileName)}</p><button class="watch-btn" type="button">Watch movie <span>→</span></button></div></article>`).join(''):'<div class="empty-state"><span>✦</span><p>No movies here yet.</p><button class="primary" onclick="openEditor()">Add your first movie</button></div>';document.querySelectorAll('.movie').forEach(c=>c.onclick=()=>openMovie(movies.find(m=>m.id===c.dataset.id)))}
function openMovie(m){activeId=m.id;if(activeUrl)URL.revokeObjectURL(activeUrl);activeUrl=URL.createObjectURL(m.file);$('#player').src=activeUrl;$('#dialogTitle').textContent=m.title;$('#dialogMeta').textContent=`${m.year||'Year unknown'} · ${m.genre||'Uncategorized'} · ${m.fileName}`;$('#dialogDescription').textContent=m.description||'No description yet.';$('#deleteMovie').onclick=async()=>{if(confirm(`Delete ${m.title}?`)){await removeMovie(m.id);$('#movieDialog').close();await load()}};$('#movieDialog').showModal()}
function stopMovie(){$('#player').pause();$('#player').removeAttribute('src');if(activeUrl){URL.revokeObjectURL(activeUrl);activeUrl=null}}
async function load(){movies=await allMovies();render()}
window.openEditor=()=>{$('#editorForm').reset();$('#formError').textContent='';$('#editorDialog').showModal()};$('#search').oninput=render;$('#editorForm').onsubmit=async e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.target));const file=data.file;if(!file||!file.size){$('#formError').textContent='Choose a movie file first.';return}try{await putMovie({id:crypto.randomUUID(),file,fileName:file.name,title:data.title.trim()||file.name.replace(/\.[^.]+$/,''),year:data.year.trim(),genre:data.genre.trim(),poster:data.poster.trim(),description:data.description.trim(),createdAt:Date.now()});$('#editorDialog').close();await load()}catch(error){$('#formError').textContent='The browser could not store this file. It may be too large for available storage.';console.error(error)}};window.addEventListener('beforeunload',stopMovie);load().catch(()=>{$('#storageNotice').textContent='This browser does not support local movie storage.'});
