services:
  earth-ex:
    build: .
    ports: ["3000:3000"]
    environment:
      ADMIN_USERNAME: Earthbound.
      ADMIN_PASSWORD: Base44.app
      MOVIES_DIR: /data/movies
      DATA_DIR: /app/data
    volumes:
      - ./media/movies:/data/movies
      - ./data:/app/data
    restart: unless-stopped
